#!/usr/bin/env bash
# Regenerates CATALOG.md from the module tree.
#
# The catalog used to be a hand-written table in README.md, and it had drifted:
# three modules missing, and a path that pointed at a directory which had been
# renamed. Deriving it from the tree means it cannot drift again.
#
#   ./tools/gen-catalog.sh          # write CATALOG.md
#   ./tools/gen-catalog.sh --check  # fail if CATALOG.md is out of date (CI)
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="CATALOG.md"
# Temp file lives next to the output: keeps the final mv on one filesystem.
TMP="$(mktemp "./.CATALOG.md.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

{
  echo "<!-- Generated by tools/gen-catalog.sh. Do not edit by hand. -->"
  echo
  echo "# Module catalog"
  echo
  echo "| Module | Type | Creates | Latest tag |"
  echo "| --- | --- | --- | --- |"

  for dir in $(find aws -mindepth 2 -maxdepth 2 -type d | sort); do
    [ -f "$dir/main.tf" ] || continue
    name="$(basename "$dir")"

    # Simple = wraps a single resource. Complex = composes several.
    # grep -h, then wc: grep -c over several files prints "file:n" per file.
    # || true because grep exits 1 on no match, and with pipefail + set -e an
    # empty result would kill the script - which is exactly what a module that
    # wraps an upstream module rather than declaring resources looks like.
    count="$( { grep -hE '^resource "' "$dir"/*.tf || true; } | wc -l | tr -d ' ')"
    if [ "$count" -le 1 ]; then type="Simple"; else type="Complex"; fi

    # An upstream-module wrapper has no resources of its own.
    if [ "$count" -eq 0 ] && grep -qE '^module "' "$dir"/*.tf; then
      type="Simple"
      creates="$( { grep -hE '^[[:space:]]+source[[:space:]]+=' "$dir"/*.tf || true; } | head -1 | sed 's/.*= *//; s/"//g')"
    else
      creates="$( { grep -hE '^resource "' "$dir"/*.tf || true; } \
        | sed 's/^resource "//; s/".*//' | sort -u | paste -sd , - | sed 's/,/, /g')"
    fi

    tag="$(git tag --list "$name/v*" --sort=-v:refname | head -1 || true)"
    [ -n "$tag" ] || tag="_unreleased_"

    echo "| [\`$dir\`]($dir) | $type | \`$creates\` | \`$tag\` |"
  done

  echo
  echo "## Using one"
  echo
  echo '```hcl'
  echo 'module "example" {'
  echo '  source = "git::https://github.com/filipe-oliveiraa/terraform-modules.git//aws/security/iam-role?ref=iam-role/v1.0.0"'
  echo '}'
  echo '```'
  echo
  echo "See [CONTRIBUTING.md](CONTRIBUTING.md) for the module contract and the release process."
} > "$TMP"

if [ "${1:-}" = "--check" ]; then
  if ! diff -q "$TMP" "$OUT" >/dev/null 2>&1; then
    echo "CATALOG.md is out of date. Run ./tools/gen-catalog.sh" >&2
    diff "$OUT" "$TMP" || true
    exit 1
  fi
  echo "CATALOG.md is up to date."
else
  mv "$TMP" "$OUT"
  trap - EXIT
  echo "Wrote $OUT"
fi
